#!/bin/bash

function send_log(){
    local user="$1"
    local iplimit="$2"
    local cekcek="$3"
    
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIFIKASI MULTI LOGIN XRAY ⚠️</b>
<code>────────────────────</code>
<code>Username : </code><code>$user</code>
<code>Limit IP : </code><code>$iplimit</code>
<code>Login IP : </code><code>$cekcek</code>
<code>────────────────────</code>
"
    curl -s --max-time 10 -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function activate_account(){
    local user="$1"
    local exp="$2"
    local type="$3"
    
    # Format penulisan berbeda untuk setiap protokol
    case $type in
        "vmess")
            echo "### $user $exp" >> /etc/xray/config.json
            echo "### $user $exp" >> /etc/vmess/.vmess.db
            ;;
        "vless")
            echo "#& $user $exp" >> /etc/xray/config.json
            echo "#& $user $exp" >> /etc/vless/.vless.db
            ;;
        "trojan")
            echo "#! $user $exp" >> /etc/xray/config.json
            echo "#! $user $exp" >> /etc/trojan/.trojan.db
            ;;
        "shadowsocks")
            echo "#!# $user $exp" >> /etc/xray/config.json
            echo "#!# $user $exp" >> /etc/shadowsocks/.shadowsocks.db
            ;;
    esac
    systemctl restart xray
}

function process_protocol(){
    local type="$1"
    local config_pattern="$2"
    local db_path="$3"
    
    for user in $(ls /etc/lunatic/limit/$type/ip/); do
        iplimit=$(cat /etc/lunatic/limit/$type/ip/$user)
        cekcek=$(grep "$user" /var/log/xray/access.log | awk '{print $3}' | sed 's/tcp://g' | cut -d: -f1 | sort -u | wc -l)

        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "$config_pattern $user" "/etc/xray/config.json" | awk '{print $3}')
            
            # Hapus konfigurasi
            sed -i "/$config_pattern $user $exp/,/},{/d" /etc/xray/config.json
            sed -i "/$config_pattern $user/d" $db_path
            rm -rf /etc/lunatic/limit/$type/ip/$user
            
            # Kirim notifikasi
            send_log "$user" "$iplimit" "$cekcek"
            
            # Jadwalkan reactivasi setelah 900 detik
            echo "activate_account \"$user\" \"$exp\" \"$type\"" | at now + 15 minutes
        fi
    done
}

# Eksekusi untuk semua protokol
process_protocol "vmess" "^###" "/etc/vmess/.vmess.db"
process_protocol "vless" "^#&" "/etc/vless/.vless.db"
process_protocol "trojan" "^#!" "/etc/trojan/.trojan.db"
process_protocol "shadowsocks" "^#!#" "/etc/shadowsocks/.shadowsocks.db"
